apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: knative-eventing-mtbroker-ingress
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: knative-eventing-mtbroker-ingress
    app.kubernetes.io/part-of: serverless-operator-release-132
  name: knative-eventing-mtbroker-ingress
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: knative-eventing-mtbroker-ingress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: knative-eventing-mtbroker-ingress
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/pdipilat-tenant/serverless-operator-release-132/knative-eventing-mtbroker-ingress@sha256:a1eb8cdd7a3bfd831a264d48018cbcb1e58e0a3643aa56a42c87173e03628740
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
